tv_topic: "tw_watching"
keys_topic: "keys_tracking"
pub_topic: "room_status_publisher/room_status"
tv_pub_topic: "room_status_publisher/tv_chair"
keys_pub_topic: "room_status_publisher/keys_location"
chair_object_name: "tv_chair"
chair_tv_location: "tv_space"
keys_object_name: "keys"
keys_location1: "living_room"
keys_location2: "bedroom"
location1x: 0.0
location1y: 0.0
location1z: 0.0
location1w: 0.0
location2x: 0.0
location2y: 0.0
location2z: 0.0
location2w: 0.0
ip: "192.168.2.10"
port: 1883
timeout: 60
username: "application"
password: "@PpL3c@tI0n"