sub_topic: "apps/localization/relative"
pub_topic: "room_status_publisher/room_status"
tv_topic: "room_status_publisher/tv_chair"
chair_object_name: "tv_chair"
chair_tv_location: "tv_space"
ip: "192.168.2.10"
port: 1883
timeout: 60
username: "application"
password: "@PpL3c@tI0n"