tv_topic: "tv_watching"
keys_topic: "keys_tracking"
pub_topic: "room_status_publisher/room_status"
tv_pub_topic: "room_status_publisher/tv_chair"
keys_pub_topic: "room_status_publisher/keys_location"
chair_object_name: "tv_chair"
chair_tv_location: "tv_space"
keys_object_name: "keys"
keys_location1: "space_1"
keys_location2: "space_2"
location1x: -0.225783845284
location1y: 0.0262244434642
location1z: 0.807974135406
location1w: 0.58921795332
location2x: -4.85505733013
location2y: 1.48312722771
location2z: 0.968967592002
location2w: 0.247187794296
ip: "192.168.2.106"
port: 1883
timeout: 60
username: "application"
password: "@PpL3c@tI0n"
write_to_file: True
